### PR TITLE
Change license to GNU GPL v3

### PR DESCRIPTION
**Pull request by BeepBot99**
The Creative Commons license is not meant for code. It is meant for assets, such as images and videos. I strongly suggest the GNU GPL v3 license. However, if you don't like it, **please** choose one of [these licenses](https://choosealicense.com/licenses/).

### CODE REVIEW

**Comment by Mesure73L** [comment]
Please provide a summary of this license.

**Comment by BeepBot99** [comment]
Sure! The GNU GPL v3 license (General Public License) is a free license. This means that it gives users freedom over what they can do. It allowed for these things:
* Commercial Use
* Redistribution
* Modification
* Private use
However, anyone distributing it must follow these conditions:
* Any redistributions and modifications must have the new source code available to the public.
* The same license must be applied.
* All modifications from the original must be stated.

**Comment by BeepBot99** [comment]
By commercial use, it means that they can use it in companies that make money. That means like, they could put ads on it to profit from it. It does not mean that they can force you to pay for it, because they must always have the source code available.

**Comment by Mesure73L** [comment]
> By commercial use, it means that they can use it in companies that make money. That means like, they could put ads on it to profit from it. It does not mean that they can force you to pay for it, because they must always have the source code available.

I know what commercial use means. I don't want that allowed.

**Review by Mesure73L — APPROVED** [review]
merge when ready

**Pull request merged**
